export const UPDATE_COURSE_SEARCH_RESULT = 'app/mainAppActions/UPDATE_COURSE_SEARCH_RESULT'
export const UPDATE_SEARCH_RESULTS_SUCCESS = 'app/mainAppActions/UPDATE_SEARCH_RESULTS_SUCCESS'
export const UPDATE_SEARCH_RESULTS_ERROR = 'app/mainAppActions/UPDATE_SEARCH_RESULTS_ERROR'
export const LOAD_ALL_COURSES = 'app/mainAppActions/LOAD_ALL_COURSES'
